[build]
  # Build command for the React frontend
  command = "cd client && npm ci && npm run build"
  
  # Output directory for the built frontend
  publish = "client/build"
  
  # Netlify Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect all API calls to Netlify Functions
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

# SPA redirect - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Headers for the frontend
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
